---
title: Python 101
author: The ATGenomics Team
copyright: "2024"
logo: imgs/logo.png
exclude_patterns: [".DS_Store", "**.ipynb_checkpoints", ".virtual_documents/", "README.md"]

execute:
  execute_notebooks: false # force

latex:
  latex_documents:
    targetname: book.tex
  latex_engine: xelatex

sphinx:
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      use_download_button: false
      show_navbar_depth: 2
      extra_footer: <a href="https://atgenomics.com">ATGenomics</a>
      toc_title: Contenido

parse:
  myst_enable_extensions:
    - html_image
    - colon_fence

html:
  favicon: imgs/favicon.ico

